# Generated by Django 3.2.8 on 2021-10-19 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joinapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_recommended_date', models.DateField(blank=True, null=True)),
                ('investor_response', models.BooleanField(blank=True, null=True)),
                ('investor_docs_sent', models.DateField(blank=True, null=True)),
                ('accepted', models.BooleanField()),
                ('approved', models.BooleanField(null=True)),
                ('renewed_declined_response', models.BooleanField(null=True)),
                ('after_maturity_mail_date', models.DateField(blank=True, null=True)),
                ('deal_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='joinapp.deal')),
                ('investment_manager_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='joinapp.investmentmanager')),
                ('investor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='joinapp.investor')),
            ],
        ),
    ]
