# Generated by Django 3.2.8 on 2021-10-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('djangomodel', '0001_initial'), ('djangomodel', '0002_product_description'), ('djangomodel', '0003_product_short_description'), ('djangomodel', '0004_remove_product_short_description')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
