# Generated by Django 3.2.8 on 2021-10-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangomodel', '0002_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
