# Generated by Django 3.2.8 on 2021-10-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangomodel', '0003_product_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
    ]
